import './location-ui.js';
import {createTownMap} from './town-map.js';
import {HudCameras} from './hud-cameras.js';
import {RideRecovery} from './ride-recovery.js';
import {RiderCamera} from './rider-camera.js';
import {laneCenter} from './road-layout.js';
import {RoadTraffic} from './traffic.js';
import {eveningLighting,enrichGround,landscapeTrees,streetLighting,parkedVehicles} from './scenery.js';
import {RoadEffects} from './effects.js';
import {addRoadside,hitBarrier} from './roadside.js';
import * as T from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {Sky} from 'three/addons/objects/Sky.js';import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';import {World} from './world.js';import {MotorcyclePhysics,clamp} from './physics.js';import {BikeAudio} from './audio.js';
const $=s=>document.querySelector(s),canvas=$('#game');canvas.style.opacity='0';const renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;
const scene=new T.Scene();scene.background=new T.Color(0xa4b5bd);scene.fog=new T.FogExp2(0xb9bdb7,.00085);const camera=new T.PerspectiveCamera(48,innerWidth/innerHeight,.10,900);const loader=new GLTFLoader();const audio=new BikeAudio(),physics=new MotorcyclePhysics(),effects=new RoadEffects(scene);const keys=new Set();let world,bike,frontWheel,rearWheel,steering,helmet,rider,brakeMat,gameReady=false,playing=false,paused=false,settings=false,camMode=0,auto=false,elapsed=0,toastTime=0,spawnKind=0,crashNotified=false,quality='high';const traffic=[];let townMap,mapOpen=false;let riderCamera,recovery,roadTraffic,dashCtx,dashTexture,updateTrees,updateStreetLights,setLighting;
const sky=new Sky();sky.scale.setScalar(15000);sky.material.uniforms.turbidity.value=3.8;sky.material.uniforms.rayleigh.value=1.1;sky.material.uniforms.mieCoefficient.value=.006;sky.material.uniforms.mieDirectionalG.value=.82;const sunVector=new T.Vector3().setFromSphericalCoords(1,T.MathUtils.degToRad(78),T.MathUtils.degToRad(238));sky.material.uniforms.sunPosition.value.copy(sunVector);scene.add(sky);const pmrem=new T.PMREMGenerator(renderer);const envScene=new T.Scene();envScene.add(sky.clone());scene.environment=pmrem.fromScene(envScene,.025).texture;pmrem.dispose();
const hemisphere=new T.HemisphereLight(0xc8dfed,0x686247,2.1);scene.add(hemisphere);const sun=new T.DirectionalLight(0xffd1a0,3.2);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-45,right:45,top:45,bottom:-45,near:1,far:350});sun.shadow.normalBias=.03;sun.shadow.bias=-.00015;scene.add(sun,sun.target);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.12,.5,1.35);composer.addPass(bloom);composer.addPass(new OutputPass());
function applyQuality(value){
 quality=value;
 renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='high'?1.7:1));
 // Canvas antialiasing does not apply to the composer's offscreen buffers.
 const samples=Math.min(quality==='high'?4:0,renderer.capabilities.maxSamples);
 for(const target of [composer.renderTarget1,composer.renderTarget2]){
  if(target.samples!==samples){target.dispose();target.samples=samples}
 }
 composer.setPixelRatio(renderer.getPixelRatio());
 bloom.enabled=quality==='high';renderer.shadowMap.enabled=quality==='high';
 renderer.shadowMap.needsUpdate=true;$('#quality').value=quality;
}
applyQuality('balanced');
// Bike meshes occupy a separate layer, so the HUD cameras see clear road views.
camera.layers.enable(1);
const hudCameras=new HudCameras(renderer,scene,$('#hud'));let hudCamerasEnabled=true;
const hudCameraSetting=document.createElement('label');hudCameraSetting.innerHTML='HUD cameras<select id="hudCameraMode"><option value="on">Three live views</option><option value="off">Off</option></select>';
$('#performance').before(hudCameraSetting);$('#hudCameraMode').onchange=e=>hudCamerasEnabled=e.target.value==='on';
const map=$('#map'),ctx=map.getContext('2d');const cameraNames=['CHASE','CINEMATIC','HELMET','COCKPIT'];
function toast(text){$('#toast').textContent=text;$('#toast').style.opacity=1;toastTime=3}
function progress(text,p){$('#loadlabel').textContent=text;$('#loadbar').style.width=p+'%'}
async function init(){try{progress('Reading the roads',10);const response=await fetch('/assets/compact-world.json');if(!response.ok)throw Error('World data failed to load');world=new World(await response.json());physics.reset(world.spawn());recovery=new RideRecovery(physics,p=>world.collision(p.x,p.z)||hitBarrier(world,p.x,p.z,p.y)||p.x<world.data.bounds[0]||p.x>world.data.bounds[2]||-p.z<world.data.bounds[1]||-p.z>world.data.bounds[3],p=>roadTraffic?.cars.some(c=>c.edge&&Math.abs(c.obj.position.y-p.y)<2&&Math.hypot(c.obj.position.x-p.x,c.obj.position.z-p.z)<4));snapCamera();townMap=createTownMap(world,(p,road)=>{const offset=laneCenter(road);p.x+=Math.cos(p.heading)*offset;p.z+=Math.sin(p.heading)*offset;physics.reset(p);recovery.reset();crashNotified=false;$('#crash').classList.add('hidden');snapCamera();toast(road.name)},open=>{mapOpen=open;keys.clear()});$('#map').onclick=()=>townMap.toggle(physics);$('#openTownMap').onclick=()=>townMap.toggle(physics);setLighting=await eveningLighting(scene,renderer,sun,sky,hemisphere);$('#lighting').onchange=e=>{setLighting(e.target.value);document.querySelector('.spec span:last-child').textContent=e.target.value==='dusk'?'BLUE HOUR':'GOLDEN HOUR'};progress('Building Shelby Township',25);await world.build(scene,loader);progress('Preparing the motorcycle',55);bike=(await loader.loadAsync('/assets/motorcycle.glb')).scene;
 bike.traverse(o=>{if(o.isMesh){o.layers.set(1);o.castShadow=true;o.receiveShadow=true;const materials=Array.isArray(o.material)?o.material:[o.material];for(const m of materials){m.envMapIntensity=.55;if(m.name==='Brake light')brakeMat=m;if(m.name==='Glass'){m.transparent=true;m.opacity=.22;m.depthWrite=false;m.metalness=0;m.roughness=.12;m.side=T.DoubleSide;m.needsUpdate=true;}if(m.name==='Textile'||m.name==='Leather'){m.color.set(0x151b20);m.roughness=.85}else if(m.name==='Pearl ceramic paint'){m.metalness=.3;m.roughness=.3}if(m.map)m.map.anisotropy=8}}});const dashCanvas=document.createElement('canvas');dashCanvas.width=512;dashCanvas.height=256;dashCtx=dashCanvas.getContext('2d');dashTexture=new T.CanvasTexture(dashCanvas);dashTexture.colorSpace=T.SRGBColorSpace;dashTexture.flipY=false;bike.traverse(o=>{if(o.isMesh){for(const m of (Array.isArray(o.material)?o.material:[o.material]))if(m.name==='Dash'){m.color.set(0xffffff);m.emissive.set(0xffffff);m.emissiveIntensity=.6;m.map=dashTexture;m.emissiveMap=dashTexture;m.needsUpdate=true}}});scene.add(bike);const headlight=new T.SpotLight(0xeaf0ff,14,45,.32,.7,1.5);headlight.position.set(0,.85,-.8);headlight.target.position.set(0,.25,-18);bike.add(headlight,headlight.target);frontWheel=bike.getObjectByName('FrontWheel');steering=bike.getObjectByName('SteeringAssembly');if(frontWheel)frontWheel.userData.restY=frontWheel.position.y;rearWheel=bike.getObjectByName('RearWheel');helmet=bike.getObjectByName('Helmet');rider=bike.getObjectByName('RiderRig');riderCamera=new RiderCamera(bike,helmet);
 const tl=new T.TextureLoader();for(const [name,prefix] of [['Textile','fabric'],['Leather','fabric'],['Tire rubber','rubber']]){const [normal,rough]=await Promise.all([tl.loadAsync('/assets/'+prefix+'-normal.png'),tl.loadAsync('/assets/'+prefix+'-roughness.png')]);for(const t of [normal,rough]){t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(12,12)}bike.traverse(o=>{if(o.isMesh){for(const m of (Array.isArray(o.material)?o.material:[o.material]))if(m.name===name){m.normalMap=normal;m.roughnessMap=rough;m.normalScale=new T.Vector2(.3,.3);m.needsUpdate=true}}})}
 progress('Adding roadside detail',68);await addRoadside(scene,world,loader);await enrichGround(scene,world,loader);updateStreetLights=streetLighting(scene,world);const bridges=(await loader.loadAsync('/assets/bridges.glb')).scene;bridges.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});scene.add(bridges);progress('Setting the traffic',75);const car=(await loader.loadAsync('/assets/sedan.glb')).scene;car.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});parkedVehicles(scene,world,car);roadTraffic=new RoadTraffic(world);await roadTraffic.build(scene,loader,car);
 progress('Planting the roadside',88);updateTrees=await landscapeTrees(scene,world,loader);reset();progress('Preparing camera views',95);await hudCameras.prepare(physics);gameReady=true;canvas.style.opacity='1';progress('Click to ride',100);$('#ride').disabled=false;$('#bottomlabel').textContent='HALL ROAD × M‑53';}catch(e){console.error(e);progress('Loading interrupted',0);$('#intro p').textContent='Could not load a required asset. Refresh to retry.';$('#bottomlabel').textContent=e.message}}
async function addTrees(){try{const model=(await loader.loadAsync('/assets/tree.glb')).scene;model.updateMatrixWorld(true);const bounds=new T.Box3().setFromObject(model),size=bounds.getSize(new T.Vector3()),scale=7.5/size.y;const locations=[];const lands=world.data.land.filter(l=>['wood','forest','grass','meadow','scrub'].includes(l.type));for(const land of lands){const pts=land.points;for(let k=0;k<Math.min(pts.length,3);k++){const p=pts[k],x=p[0],z=-p[1],road=world.roadAt(x,z);if(Math.abs(x)>1650||Math.abs(z)>1650||world.collision(x,z)||road&&road.distance<road.road.width/2+8)continue;locations.push([x,world.elevation(x,z),z]);if(locations.length>=55)break}if(locations.length>=55)break}
 const farPositions=[];let seed=811;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};const inside=(x,y,pts)=>{let c=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++)if((pts[i][1]>y)!==(pts[j][1]>y)&&x<(pts[j][0]-pts[i][0])*(y-pts[i][1])/(pts[j][1]-pts[i][1])+pts[i][0])c=!c;return c};for(const land of lands.filter(l=>['wood','forest','scrub'].includes(l.type))){const xs=land.points.map(p=>p[0]),ys=land.points.map(p=>p[1]),loX=Math.max(-1660,Math.min(...xs)),hiX=Math.min(1660,Math.max(...xs)),loY=Math.max(-1660,Math.min(...ys)),hiY=Math.min(1660,Math.max(...ys));const count=Math.min(300,Math.floor((hiX-loX)*(hiY-loY)/160));for(let i=0;i<count;i++){const x=loX+random()*(hiX-loX),y=loY+random()*(hiY-loY),r=world.roadAt(x,-y);if(!inside(x,y,land.points)||world.collision(x,-y)||r&&r.distance<r.road.width/2+12)continue;farPositions.push(x,world.elevation(x,-y)+4,-y)}}const treeMap=await new T.TextureLoader().loadAsync('/assets/tree-impostor.png');treeMap.colorSpace=T.SRGBColorSpace;const treePoints=new T.BufferGeometry();treePoints.setAttribute('position',new T.Float32BufferAttribute(farPositions,3));const woods=new T.Points(treePoints,new T.PointsMaterial({map:treeMap,color:0xbfc5ac,size:8,alphaTest:.45,transparent:false,sizeAttenuation:true}));scene.add(woods);
 const dummy=new T.Object3D(),matrix=new T.Matrix4();model.traverse(o=>{if(o.isMesh){const m=o.material.clone();m.side=T.DoubleSide;m.alphaTest=.45;m.transparent=false;const inst=new T.InstancedMesh(o.geometry,m,locations.length);locations.forEach((p,i)=>{dummy.position.set(...p);dummy.rotation.y=i*2.399;dummy.scale.setScalar(scale*(.8+(i%4)*.12));dummy.updateMatrix();matrix.multiplyMatrices(dummy.matrix,o.matrixWorld);inst.setMatrixAt(i,matrix)});inst.castShadow=true;inst.receiveShadow=true;inst.instanceMatrix.needsUpdate=true;scene.add(inst)}})}catch(e){console.warn('Roadside vegetation unavailable',e)}}
function reset(){if(!world)return;const spawn=world.spawn(spawnKind);spawn.y=world.ground(spawn.x,spawn.z,spawn.y).height;physics.reset(spawn);recovery?.reset();crashNotified=false;$('#crash').classList.add('hidden');if(bike)bike.position.set(physics.x,physics.y,physics.z);snapCamera();toast(playing?'Ready to ride':'')}
function recover(){if(recovery?.recover()){crashNotified=false;keys.clear();$('#crash').classList.add('hidden');$('#recover').blur();$('#recoveryHint').textContent='Restart nearby · or press R';toast('Ready to ride')}else if(physics.crashed){$('#recoveryHint').textContent='Traffic is blocking your safe spot. Try again in a moment.'}}
function snapCamera(){cameraHasPrevious=false;const p=physics;camera.position.set(p.x-Math.sin(p.heading)*6+Math.cos(p.heading)*2,p.y+2.6,p.z+Math.cos(p.heading)*6+Math.sin(p.heading)*2);camera.lookAt(p.x,p.y+.8,p.z)}
function toggleSettings(){settings=!settings;$('#settings').classList.toggle('hidden',!settings);keys.clear()}
$('#ride').onclick=async()=>{if(!gameReady)return;await audio.start();if(!audio.available)toast('Audio unavailable in this browser');playing=true;document.body.classList.add('riding');$('#hud').classList.remove('hidden');$('#topStatus').classList.remove('hidden');$('#hints').classList.remove('hidden');$('#intro').setAttribute('aria-hidden','true');$('#ride').blur();toast('E to shift up · C to change camera')};$('#settingsBtn').onclick=toggleSettings;$('#closeSettings').onclick=toggleSettings;$('#reset').onclick=recover;$('#recover').onclick=recover;$('#spawn').onchange=e=>{spawnKind=+e.target.value;reset()};$('#cameraSelect').onchange=e=>{camMode=+e.target.value;$('#cameraName').textContent=cameraNames[camMode];cameraHasPrevious=false};$('#quality').onchange=e=>{applyQuality(e.target.value)};$('#transmission').onchange=e=>auto=e.target.value==='auto';$('#mute').onclick=()=>{audio.muted=!audio.muted;$('#mute').textContent=audio.muted?'Off':'On'};
function shift(dir){if(physics.shift(dir)){audio.impact(.045);toast(dir>0?'SHIFT UP':'SHIFT DOWN')}}
addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(document.activeElement.tagName))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='KeyM'&&townMap){townMap.toggle(physics);return}if(e.code==='Escape'){if(townMap?.isOpen()){townMap.toggle();return}toggleSettings();}if(!playing)return;if(e.code==='KeyC'){camMode=(camMode+1)%4;$('#cameraName').textContent=cameraNames[camMode];toast(cameraNames[camMode])}if(e.code==='KeyE')shift(1);if(e.code==='KeyQ')shift(-1);if(e.code==='KeyR')recover();if(e.code==='KeyP'){paused=!paused;$('#pause').classList.toggle('hidden',!paused)}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();if(playing){paused=true;$('#pause').classList.remove('hidden')}});
const down=(...codes)=>codes.some(c=>keys.has(c));let padLast=[];
function input(){const i={throttle:down('KeyW','ArrowUp')?1:0,brake:down('KeyS','ArrowDown')?1:0,reverse:down('KeyS','ArrowDown')?1:0,steer:(down('KeyD','ArrowRight')?1:0)-(down('KeyA','ArrowLeft')?1:0),clutch:down('ShiftLeft','ShiftRight')?1:0,rearBrake:down('Space')?1:0};i.brake=Math.max(i.brake,i.rearBrake*.7);const pad=navigator.getGamepads?.()[0];if(pad){i.throttle=Math.max(i.throttle,pad.buttons[7]?.value||0);i.brake=Math.max(i.brake,pad.buttons[6]?.value||0);if(Math.abs(pad.axes[0])>.08)i.steer=pad.axes[0];if(pad.buttons[0].pressed&&!padLast[0])shift(1);if(pad.buttons[1].pressed&&!padLast[1])shift(-1);if(pad.buttons[3].pressed&&!padLast[3]){camMode=(camMode+1)%4;$('#cameraName').textContent=cameraNames[camMode]}padLast=pad.buttons.map(b=>b.pressed)}return i}
function updateTraffic(dt){for(const t of traffic){const p=physics;if(Math.hypot(t.obj.position.x-p.x,t.obj.position.z-p.z)<18)t.speed+=(3-t.speed)*dt;else t.speed+=(t.road.class==='motorway'?24-t.speed:16-t.speed)*dt*.4;t.distance+=t.speed*dt;if(t.distance>t.road.length){const node=t.road.nodeIds.at(-1);const next=world.data.roads.filter(r=>r!==t.road&&r.oneway&&r.nodeIds[0]===node&&['motorway','trunk','motorway_link','trunk_link'].includes(r.class));t.road=next[0]||t.road;t.distance=0}const r=t.road;let idx=1;while(idx<r.distances.length-1&&r.distances[idx]<t.distance)idx++;const a=r.points[idx-1],b=r.points[idx],f=clamp((t.distance-r.distances[idx-1])/(r.distances[idx]-r.distances[idx-1]),0,1),heading=Math.atan2(b[0]-a[0],b[1]-a[1]);t.obj.position.set(a[0]+(b[0]-a[0])*f+Math.cos(heading)*1.8,a[2]+(b[2]-a[2])*f,-a[1]-(b[1]-a[1])*f+Math.sin(heading)*1.8);t.obj.rotation.y=-heading;if(playing&&!p.crashed&&Math.hypot(t.obj.position.x-p.x,t.obj.position.z-p.z)<2&&Math.abs(t.obj.position.y-p.y)<2)p.crash()}}
const camTarget=new T.Vector3(),look=new T.Vector3(),cameraOffset=new T.Vector3(),previousCameraBike=new T.Vector3();let cameraHasPrevious=false;const ray=new T.Raycaster();
function updateCamera(dt){const p=physics,forward=new T.Vector3(Math.sin(p.heading),0,-Math.cos(p.heading)),right=new T.Vector3(Math.cos(p.heading),0,Math.sin(p.heading));if(!playing){const angle=p.heading+.7+Math.sin(elapsed*.09)*.12;camTarget.set(p.x+Math.sin(angle)*4.1,p.y+1.55,p.z-Math.cos(angle)*4.1);look.set(p.x,p.y+.86,p.z);camera.position.lerp(camTarget,1-Math.exp(-dt*2));camera.lookAt(look);camera.setViewOffset(innerWidth,innerHeight,-innerWidth*.18,0,innerWidth,innerHeight);return}camera.clearViewOffset();camera.near=camMode>=2?.06:.10;if(cameraHasPrevious&&camMode<2)camera.position.add(new T.Vector3(p.x,p.y,p.z).sub(previousCameraBike));previousCameraBike.set(p.x,p.y,p.z);cameraHasPrevious=true;
 if(camMode<2){const distance=camMode===0?4.7:3.2;camTarget.set(p.x,p.y+(camMode===0?1.95:1.2),p.z).addScaledVector(forward,-distance).addScaledVector(right,camMode===1?1.35:.45);look.set(p.x,p.y+.9,p.z).addScaledVector(forward,3.2+p.speed*.045);camera.position.lerp(camTarget,1-Math.exp(-dt*(camMode===0?5:3)));camera.position.y=Math.max(camera.position.y,world.elevation(camera.position.x,camera.position.z)+.65);if(world.collision(camera.position.x,camera.position.z)){camera.position.lerp(new T.Vector3(p.x,p.y+2.2,p.z),.75)}camera.lookAt(look);camera.rotation.z+=p.lean*.07}else{riderCamera.update(camera,camMode)}camera.fov+=(clamp((camMode>=2?64:50)+p.speed*.15,camMode>=2?64:50,camMode>=2?75:66)-camera.fov)*Math.min(1,dt*3);camera.updateProjectionMatrix();if(helmet)helmet.visible=camMode!==2&&camMode!==3;if(rider)rider.visible=true;
}
function miniMap(){if(!world)return;ctx.clearRect(0,0,240,180);ctx.save();ctx.translate(120,90);ctx.rotate(-physics.heading);const s=.20;ctx.strokeStyle='#c6cfcc65';ctx.lineWidth=1.3;for(const r of world.data.roads){if(r.class==='service'||r.bounds[2]<physics.x-800||r.bounds[0]>physics.x+800||r.bounds[3]<-physics.z-800||r.bounds[1]>-physics.z+800)continue;ctx.beginPath();r.points.forEach((p,i)=>{const x=(p[0]-physics.x)*s,y=(-p[1]-physics.z)*s;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}ctx.restore();ctx.fillStyle='#efb277';ctx.beginPath();ctx.moveTo(120,81);ctx.lineTo(115,95);ctx.lineTo(120,92);ctx.lineTo(125,95);ctx.closePath();ctx.fill();ctx.fillStyle='#e4e8da';ctx.font='9px Manrope';ctx.fillText('N',224,18)}
let fpsFrames=0,fpsTime=0;let last=performance.now(),accumulator=0,hudTime=0;function frame(now){requestAnimationFrame(frame);const rawDt=(now-last)/1000,dt=Math.min(rawDt,.05);last=now;elapsed+=dt;fpsFrames++;fpsTime+=rawDt;if(fpsTime>=1){$('#performance').textContent=Math.round(fpsFrames/fpsTime)+' FPS · '+quality+' rendering';fpsFrames=0;fpsTime=0}if(gameReady){if(playing&&!paused&&!settings&&!mapOpen){const inp=input();accumulator+=dt;while(accumulator>=1/120){const p=physics;const ground=world.ground(p.x,p.z,p.y);const ahead=world.ground(p.x+Math.sin(p.heading)*1.4,p.z-Math.cos(p.heading)*1.4,p.y);ground.slope=clamp((ahead.height-ground.height)/1.4,-.25,.25);recovery.step(1/120,inp,ground);if(auto&&!p.reversing&&!p.shiftCut){if(p.rpm>8500&&p.gear<6)shift(1);else if(p.rpm<3000&&p.gear>1)shift(-1)}accumulator-=1/120;}roadTraffic.update(dt,physics);effects.update(dt,physics);if(physics.crashed&&!crashNotified){audio.impact(.8);crashNotified=true;keys.clear();$('#crash').classList.remove('hidden');$('#recover').focus({preventScroll:true})}else if(!physics.crashed)crashNotified=false;audio.update(physics,camMode)}else audio.update({...physics,throttle:0,speed:0,rpm:1300},camMode);
 const p=physics;bike.position.set(p.x,p.y+p.suspension+.03,p.z);bike.rotation.set(p.pitch-p.wheelie,-p.heading,p.lean,'YXZ');if(frontWheel){frontWheel.rotation.x-=(p.reversing?-p.speed:p.speed)/.305*dt*((paused||settings||!playing)?0:1);frontWheel.position.y=frontWheel.userData.restY-p.suspension*.45;if(steering)steering.rotation.y=-p.steer*.34/(1+p.speed/8)}if(rearWheel)rearWheel.rotation.x-=(p.reversing?-p.speed:p.speed)/.305*dt*((paused||settings||!playing)?0:1);if(helmet)helmet.rotation.y=p.steer*.045;if(brakeMat)brakeMat.emissiveIntensity=p.brake>0?5:1;sun.position.set(p.x+sunVector.x*150,p.y+sunVector.y*150+40,p.z+sunVector.z*150);sun.target.position.set(p.x,p.y,p.z);updateCamera(dt);if(world.updateBuildings)world.updateBuildings(p);if(roadTraffic)roadTraffic.updateSignals(p);if(updateTrees)updateTrees(camera);if(updateStreetLights)updateStreetLights(p);hudTime+=dt;if(hudTime>.1){hudTime=0;if(dashCtx){dashCtx.fillStyle='#09121a';dashCtx.fillRect(0,0,512,256);dashCtx.fillStyle='#dfebe4';dashCtx.font='bold 110px Arial';dashCtx.fillText(Math.round(p.speed*2.23694),30,165);dashCtx.font='90px Arial';dashCtx.fillText(p.reversing?'R':p.gear||'N',385,165);dashCtx.font='20px Arial';dashCtx.fillText('MPH',38,198);dashCtx.fillText('GEAR',378,198);dashCtx.fillStyle='#f2a965';dashCtx.fillRect(30,35,440*p.rpm/11200,12);dashTexture.needsUpdate=true;}$('#speed').textContent=Math.round(p.speed*2.23694);$('#rpm').textContent=(p.rpm/1000).toFixed(1);$('#gear').textContent=p.reversing?'R':p.gear||'N';$('#tachfill').style.width=(p.rpm/11200*100)+'%';$('#tachfill').style.background=p.rpm>9800?'#ff6f4b':'#e9b47c';const road=world.ground(p.x,p.z,p.y);$('#roadname').textContent=(road.road?.name||'SHELBY TOWNSHIP').toUpperCase();$('#surface').textContent=road.onRoad?'':road.surface.toUpperCase();$('#distance').textContent=(p.distance/1609.34).toFixed(1)+' MI';miniMap()}if(p.distance>120)$('#hints').style.opacity=0;}
 if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('#toast').style.opacity=0}if(quality==='high')composer.render();else renderer.render(scene,camera);
 if(gameReady&&playing)hudCameras.render(now,rawDt,physics,{quality,visible:hudCamerasEnabled&&!mapOpen&&!settings,live:!paused&&!physics.crashed});}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight)});requestAnimationFrame(frame);init();
